scrape_configs:
  - job_name: 'nodes'
    tls_config:
      ca_file: ca.pem
      cert_file: prometheus.pem
      key_file: prometheus-key.pem
    scheme: https
    params:
      exporter-port:
        - "9100"
    static_configs:
    - targets: ['127.0.0.1:9443']
    relabel_configs:
    - source_labels: [__address__]
      regex: ^(.*):(.*)$
      target_label: instance
